version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - './api:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - FLASK_CONFIG=development
      - FLASK_ENV=development

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - api
      - ui

  ui:
    build:
      context: ./nginx/data_visualization
      dockerfile: Dockerfile.dev
    volumes:
      - './nginx/data_visualization:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - api


volumes:
  db-data: